os:
  - linux
  - osx
language: csharp
solution: GwenCS/GwenNet.sln
before_script:
  - mono .paket/paket-bootstrapper.exe
  - mono .paket/paket.exe restore
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
